barathonuser_space:
    resource: "@BarathonuserSpaceBundle/Resources/config/routing.yml"
    prefix:   /

barathon_index:
    resource: "@BarathonIndexBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"