# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

#services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    app.form.registration:
        class:  Barathon\IndexBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }