test_front_page:
    path: /
    defaults: { _controller: BarathonuserSpaceBundle:HomePage:homePage }

profil_user:
    path: /profil
    defaults: { _controller: BarathonuserSpaceBundle:Profil:profil }

event_user:
    path: /event
    defaults: { _controller: BarathonuserSpaceBundle:Event:event }

message_user:
    path: /message
    defaults: { _controller: BarathonuserSpaceBundle:Message:message }

bar_user:
    path: /bar
    defaults: {_controller: BarathonuserSpaceBundle:Bar:bar }